
package ru.gosuslugi.dom.schema.integration._8_5_0_4.services_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import ru.gosuslugi.dom.schema.integration._8_5_0.ImportResult;
import ru.gosuslugi.dom.schema.integration._8_5_0.RequestHeader;
import ru.gosuslugi.dom.schema.integration._8_5_0.ResultHeader;
import ru.gosuslugi.dom.schema.integration._8_5_0_4.services.ExportCompletedWorksRequest;
import ru.gosuslugi.dom.schema.integration._8_5_0_4.services.ExportCompletedWorksResult;
import ru.gosuslugi.dom.schema.integration._8_5_0_4.services.ExportHMServicesTarifsRequest;
import ru.gosuslugi.dom.schema.integration._8_5_0_4.services.ExportHMServicesTarifsResult;
import ru.gosuslugi.dom.schema.integration._8_5_0_4.services.ExportMSRSORequest;
import ru.gosuslugi.dom.schema.integration._8_5_0_4.services.ExportMSRSOResult;
import ru.gosuslugi.dom.schema.integration._8_5_0_4.services.ExportWorkingListRequest;
import ru.gosuslugi.dom.schema.integration._8_5_0_4.services.ExportWorkingListResult;
import ru.gosuslugi.dom.schema.integration._8_5_0_4.services.ExportWorkingPlanRequest;
import ru.gosuslugi.dom.schema.integration._8_5_0_4.services.ExportWorkingPlanResult;
import ru.gosuslugi.dom.schema.integration._8_5_0_4.services.ImportCompletedWorksRequest;
import ru.gosuslugi.dom.schema.integration._8_5_0_4.services.ImportHMServicesTarifsRequest;
import ru.gosuslugi.dom.schema.integration._8_5_0_4.services.ImportMSRSORequest;
import ru.gosuslugi.dom.schema.integration._8_5_0_4.services.ImportWorkingListRequest;
import ru.gosuslugi.dom.schema.integration._8_5_0_4.services.ImportWorkingPlanRequest;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicesPortsType", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/services-service/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration._8_5_0_4.services.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration._8_5_0.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class
})
public interface ServicesPortsType {


    /**
     * ВИ_ИПОЧ_УК_ТФ_ИМП. импорт тарифов ЖКУ
     * 
     * @param header0
     * @param header
     * @param importHMServicesTarifsDataRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_5_0.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importHMServicesTarifs")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", partName = "importHMServicesTarifsDataResult")
    public ImportResult importHMServicesTarifs(
        @WebParam(name = "importHMServicesTarifsRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/services/", partName = "importHMServicesTarifsDataRequest")
        ImportHMServicesTarifsRequest importHMServicesTarifsDataRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_ИПОЧ_УК_ТФ_ЭКСП. экспорт тарифов ЖКУ
     * 
     * @param header0
     * @param exportHMServicesTarifsDataRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_5_0_4.services.ExportHMServicesTarifsResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportHMServicesTarifs")
    @WebResult(name = "exportHMServicesTarifsResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/services/", partName = "exportHMServicesTarifsDataResult")
    public ExportHMServicesTarifsResult exportHMServicesTarifs(
        @WebParam(name = "exportHMServicesTarifsRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/services/", partName = "exportHMServicesTarifsDataRequest")
        ExportHMServicesTarifsRequest exportHMServicesTarifsDataRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_ИРАО_КУРСО_ИМП. Импорт КУ по прямым договорам с РСО.
     * 
     * @param importMSRSODataRequest
     * @param header0
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_5_0.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importMSRSO")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", partName = "importMSRSODataResult")
    public ImportResult importMSRSO(
        @WebParam(name = "importMSRSORequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/services/", partName = "importMSRSODataRequest")
        ImportMSRSORequest importMSRSODataRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_ИРАО_КУРСО_ЭКСП. Экспорт КУ по прямым договорам с РСО.
     * 
     * @param header0
     * @param header
     * @param exportMSRSODataRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_5_0_4.services.ExportMSRSOResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportMSRSO")
    @WebResult(name = "exportMSRSOResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/services/", partName = "exportMSRSODataResult")
    public ExportMSRSOResult exportMSRSO(
        @WebParam(name = "exportMSRSORequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/services/", partName = "exportMSRSODataRequest")
        ExportMSRSORequest exportMSRSODataRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_ИПФР_ПЕР_ЭКСП. экспорт основных сведений по перечню работ
     * 
     * @param header0
     * @param exportWorkingListRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_5_0_4.services.ExportWorkingListResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportWorkingList")
    @WebResult(name = "exportWorkingListResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/services/", partName = "exportWorkingListResult")
    public ExportWorkingListResult exportWorkingList(
        @WebParam(name = "exportWorkingListRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/services/", partName = "exportWorkingListRequest")
        ExportWorkingListRequest exportWorkingListRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_ИПФР_ПЕР_ИМП. импорт основных сведений по перечню работ
     * 
     * @param importWorkingListRequest
     * @param header0
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_5_0.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importWorkingList")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", partName = "importWorkingListResult")
    public ImportResult importWorkingList(
        @WebParam(name = "importWorkingListRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/services/", partName = "importWorkingListRequest")
        ImportWorkingListRequest importWorkingListRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_ИПФР_ПЛАН_ИМП. импорт актуальных планов по перечню работ/услуг
     * 
     * @param importWorkingPlanRequest
     * @param header0
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_5_0.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importWorkingPlan")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", partName = "importWorkingPlanResult")
    public ImportResult importWorkingPlan(
        @WebParam(name = "importWorkingPlanRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/services/", partName = "importWorkingPlanRequest")
        ImportWorkingPlanRequest importWorkingPlanRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_ИПФР_ПЛАН_ЭКСП. экспорт актуальных планов по перечню работ/услуг
     * 
     * @param header0
     * @param header
     * @param exportWorkingPlanRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_5_0_4.services.ExportWorkingPlanResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportWorkingPlan")
    @WebResult(name = "exportWorkingPlanResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/services/", partName = "exportWorkingPlanResult")
    public ExportWorkingPlanResult exportWorkingPlan(
        @WebParam(name = "exportWorkingPlanRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/services/", partName = "exportWorkingPlanRequest")
        ExportWorkingPlanRequest exportWorkingPlanRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_ИПФР_ВЫП_ИМП. импорт сведений о выполненных работах и услугах
     * 
     * @param importCompletedWorksRequest
     * @param header0
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_5_0.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importCompletedWorks")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", partName = "importCompletedWorksResult")
    public ImportResult importCompletedWorks(
        @WebParam(name = "importCompletedWorksRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/services/", partName = "importCompletedWorksRequest")
        ImportCompletedWorksRequest importCompletedWorksRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_ИПФР_ВЫП_ЭКСП. экспорт сведений о выполненных работах и услугах
     * 
     * @param header0
     * @param exportCompletedWorksRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_5_0_4.services.ExportCompletedWorksResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportCompletedWorks")
    @WebResult(name = "exportCompletedWorksResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/services/", partName = "exportCompletedWorksResult")
    public ExportCompletedWorksResult exportCompletedWorks(
        @WebParam(name = "exportCompletedWorksRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/services/", partName = "exportCompletedWorksRequest")
        ExportCompletedWorksRequest exportCompletedWorksRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

}
