
package ru.gosuslugi.dom.schema.integration._8_5_0_4.device_metering_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import ru.gosuslugi.dom.schema.integration._8_5_0.ImportResult;
import ru.gosuslugi.dom.schema.integration._8_5_0.RequestHeader;
import ru.gosuslugi.dom.schema.integration._8_5_0.ResultHeader;
import ru.gosuslugi.dom.schema.integration._8_5_0_4.device_metering.ExportMeteringDeviceHistoryRequest;
import ru.gosuslugi.dom.schema.integration._8_5_0_4.device_metering.ExportMeteringDeviceHistoryResult;
import ru.gosuslugi.dom.schema.integration._8_5_0_4.device_metering.ImportMeteringDeviceValuesRequest;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DeviceMeteringPortTypes", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/device-metering-service/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration._8_5_0_4.device_metering.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration._8_5_0.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class
})
public interface DeviceMeteringPortTypes {


    /**
     * Передать показания ПУ
     * 
     * @param importMeteringDeviceValuesRequest
     * @param header0
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_5_0.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importMeteringDeviceValues")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", partName = "ImportResult")
    public ImportResult importMeteringDeviceValues(
        @WebParam(name = "importMeteringDeviceValuesRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/device-metering/", partName = "importMeteringDeviceValuesRequest")
        ImportMeteringDeviceValuesRequest importMeteringDeviceValuesRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * Получить историю показаний ПУ
     * 
     * @param header0
     * @param header
     * @param exportMeteringDeviceHistoryRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_5_0_4.device_metering.ExportMeteringDeviceHistoryResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportMeteringDeviceHistory")
    @WebResult(name = "exportMeteringDeviceHistoryResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/device-metering/", partName = "exportMeteringDeviceHistoryResult")
    public ExportMeteringDeviceHistoryResult exportMeteringDeviceHistory(
        @WebParam(name = "exportMeteringDeviceHistoryRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/device-metering/", partName = "exportMeteringDeviceHistoryRequest")
        ExportMeteringDeviceHistoryRequest exportMeteringDeviceHistoryRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

}
