
package ru.gosuslugi.dom.schema.integration._8_5_0_2.bills_service;

import ru.gosuslugi.dom.schema.integration._8_5_0.ImportResult;
import ru.gosuslugi.dom.schema.integration._8_5_0.RequestHeader;
import ru.gosuslugi.dom.schema.integration._8_5_0.ResultHeader;
import ru.gosuslugi.dom.schema.integration._8_5_0_2.bills.*;

import javax.jws.*;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BillsPortsType", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.2/bills-service/")
@HandlerChain(file = "ClientMessage_handler.xml")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration._8_5_0_2.bills.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration._8_5_0.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class
})
public interface BillsPortsType {


    /**
     * ВИ_ИЛС_РПО_ОТК. открыть расчетный период организации
     * 
     * @param openOrgPaymentPeriodRequest
     * @param header0
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_5_0.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:openOrgPaymentPeriod")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.2/", partName = "openOrgPaymentPeriodResult")
    public ImportResult openOrgPaymentPeriod(
        @WebParam(name = "openOrgPaymentPeriodRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.2/bills/", partName = "openOrgPaymentPeriodRequest")
        OpenOrgPaymentPeriodRequest openOrgPaymentPeriodRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.2/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.2/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_ИЛС_РПД_ЗАК. закрыть расчетный период дома
     * 
     * @param closeHousePaymentPeriodRequest
     * @param header0
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_5_0.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:closeHousePaymentPeriod")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.2/", partName = "closeHousePaymentPeriodResult")
    public ImportResult closeHousePaymentPeriod(
        @WebParam(name = "closeHousePaymentPeriodRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.2/bills/", partName = "closeHousePaymentPeriodRequest")
        CloseHousePaymentPeriodRequest closeHousePaymentPeriodRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.2/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.2/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_ИЛС_ПД_ИМП. импорт платежных документов
     * 
     * @param header0
     * @param importPaymentDocumentDataRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_5_0.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importPaymentDocumentData")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.2/", partName = "importPaymentDocumentDataResult")
    public ImportResult importPaymentDocumentData(
        @WebParam(name = "importPaymentDocumentRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.2/bills/", partName = "importPaymentDocumentDataRequest")
        ImportPaymentDocumentRequest importPaymentDocumentDataRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.2/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.2/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_ИЛС_ПД_ЭКСП. экспорт платежных документов
     * 
     * @param header0
     * @param exportPaymentDocumentDataRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_5_0_2.bills.ExportPaymentDocumentResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportPaymentDocumentData")
    @WebResult(name = "exportPaymentDocumentResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.2/bills/", partName = "exportPaymentDocumentDataResult")
    public ExportPaymentDocumentResult exportPaymentDocumentData(
        @WebParam(name = "exportPaymentDocumentRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.2/bills/", partName = "exportPaymentDocumentDataRequest")
        ExportPaymentDocumentRequest exportPaymentDocumentDataRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.2/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.2/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_ИЛС_РПО_ЭКСП. получить расчетные периоды организации
     * 
     * @param header0
     * @param exportOrgPeriodDataRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_5_0_2.bills.ExportOrgPeriodResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportOrgPeriodData")
    @WebResult(name = "exportOrgPeriodResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.2/bills/", partName = "exportOrgPeriodDataResult")
    public ExportOrgPeriodResult exportOrgPeriodData(
        @WebParam(name = "exportOrgPeriodRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.2/bills/", partName = "exportOrgPeriodDataRequest")
        ExportOrgPeriodRequest exportOrgPeriodDataRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.2/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.2/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

}
