
package ru.gosuslugi.dom.schema.integration._8_6_0_4.organizations_registry_common_service;

import javax.jws.*;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import ru.gosuslugi.dom.schema.integration._8_6_0.ISRequestHeader;
import ru.gosuslugi.dom.schema.integration._8_6_0.ImportResult;
import ru.gosuslugi.dom.schema.integration._8_6_0.ResultHeader;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.organizations_registry_common.ExportDataProviderRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.organizations_registry_common.ExportDataProviderResult;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.organizations_registry_common.ExportOrgRegistryRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.organizations_registry_common.ExportOrgRegistryResult;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.organizations_registry_common.ImportDataProviderRequest;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RegOrgPortsType", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/organizations-registry-common-service/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@HandlerChain(file = "handler/ClientMessage_handler.xml")
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration._8_6_0_4.organizations_registry_common.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration._8_6_0.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class
})
public interface RegOrgPortsType {


    /**
     * экспорт сведений об организациях
     * 
     * @param exportOrgRegistryRequest
     * @param header0
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0_4.organizations_registry_common.ExportOrgRegistryResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportOrgRegistry")
    @WebResult(name = "exportOrgRegistryResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/organizations-registry-common/", partName = "exportOrgRegistryResult")
    public ExportOrgRegistryResult exportOrgRegistry(
        @WebParam(name = "exportOrgRegistryRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/organizations-registry-common/", partName = "exportOrgRegistryRequest")
        ExportOrgRegistryRequest exportOrgRegistryRequest,
        @WebParam(name = "ISRequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, partName = "Header")
        ISRequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * импорт сведений о поставщиках данных
     * 
     * @param header0
     * @param header
     * @param importDataProviderRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importDataProvider")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", partName = "ImportResult")
    public ImportResult importDataProvider(
        @WebParam(name = "importDataProviderRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/organizations-registry-common/", partName = "importDataProviderRequest")
        ImportDataProviderRequest importDataProviderRequest,
        @WebParam(name = "ISRequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, partName = "Header")
        ISRequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * экспорт сведений о поставщиках данных
     * 
     * @param tnsExportDataProviderRequest
     * @param header0
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0_4.organizations_registry_common.ExportDataProviderResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportDataProvider")
    @WebResult(name = "exportDataProviderResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/organizations-registry-common/", partName = "tns:exportDataProviderResult")
    public ExportDataProviderResult exportDataProvider(
        @WebParam(name = "exportDataProviderRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/organizations-registry-common/", partName = "tns:exportDataProviderRequest")
        ExportDataProviderRequest tnsExportDataProviderRequest,
        @WebParam(name = "ISRequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, partName = "Header")
        ISRequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

}
