
package ru.gosuslugi.dom.schema.integration._8_6_0_4.house_management_service_async;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import ru.gosuslugi.dom.schema.integration._8_6_0.AckRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0.GetStateRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0.RequestHeader;
import ru.gosuslugi.dom.schema.integration._8_6_0.ResultHeader;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.house_management.ExportAccountRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.house_management.ExportCAChRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.house_management.ExportHouseRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.house_management.ExportMeteringDeviceDataRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.house_management.ExportShareEncbrDataRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.house_management.ExportStatusCAChRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.house_management.ExportStatusPublicPropertyContractRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.house_management.ExportVotingProtocolRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.house_management.GetStateResult;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.house_management.ImportAccountRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.house_management.ImportCharterRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.house_management.ImportContractRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.house_management.ImportHouseOMSRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.house_management.ImportHouseRSORequest;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.house_management.ImportHouseUORequest;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.house_management.ImportMeteringDeviceDataRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.house_management.ImportNotificationRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.house_management.ImportPublicPropertyContractRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.house_management.ImportShareEncbrDataRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.house_management.ImportVotingProtocolRequest;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HouseManagementPortsTypeAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/house-management-service-async/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration._8_6_0_4.house_management.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration._8_6_0.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class
})
public interface HouseManagementPortsTypeAsync {


    /**
     * Передать данные ПУ
     * 
     * @param header0
     * @param importMeteringDeviceDataRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importMeteringDeviceData")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", partName = "AckRequest")
    public AckRequest importMeteringDeviceData(
        @WebParam(name = "importMeteringDeviceDataRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/house-management/", partName = "importMeteringDeviceDataRequest")
        ImportMeteringDeviceDataRequest importMeteringDeviceDataRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * Получить перечень ПУ
     * 
     * @param header0
     * @param header
     * @param exportMeteringDeviceDataRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportMeteringDeviceData")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", partName = "AckRequest")
    public AckRequest exportMeteringDeviceData(
        @WebParam(name = "exportMeteringDeviceDataRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/house-management/", partName = "exportMeteringDeviceDataRequest")
        ExportMeteringDeviceDataRequest exportMeteringDeviceDataRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * 
     * @param getStateRequest
     * @param header0
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0_4.house_management.GetStateResult
     * @throws Fault
     */
    @WebMethod(action = "urn:getState")
    @WebResult(name = "getStateResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/house-management/", partName = "getStateResult")
    public GetStateResult getState(
        @WebParam(name = "getStateRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", partName = "getStateRequest")
        GetStateRequest getStateRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_ИРАО_ИМП_ДОЛЯОБР. Импорт долей собственности и обременений.
     * 
     * @param importShareEncbrDataRequest
     * @param header0
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importShareEncbrData")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", partName = "AckRequest")
    public AckRequest importShareEncbrData(
        @WebParam(name = "importShareEncbrDataRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/house-management/", partName = "importShareEncbrDataRequest")
        ImportShareEncbrDataRequest importShareEncbrDataRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_ИРАО_ЭКСП_ДОЛЯОБР. Экспорт долей собственности и обременений.
     * 
     * @param header0
     * @param header
     * @param exportShareEncbrDataRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportShareEncbrData")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", partName = "AckRequest")
    public AckRequest exportShareEncbrData(
        @WebParam(name = "exportShareEncbrDataRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/house-management/", partName = "exportShareEncbrDataRequest")
        ExportShareEncbrDataRequest exportShareEncbrDataRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * Cоздание/редактирование, удаление, пролонгация, расторжение ДУ
     * 
     * @param header0
     * @param header
     * @param importContractRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importContractData")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", partName = "AckRequest")
    public AckRequest importContractData(
        @WebParam(name = "importContractRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/house-management/", partName = "importContractRequest")
        ImportContractRequest importContractRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * Cоздание/редактирование, удаление, пролонгация, расторжение устава
     * 
     * @param importCharterRequest
     * @param header0
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importCharterData")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", partName = "AckRequest")
    public AckRequest importCharterData(
        @WebParam(name = "importCharterRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/house-management/", partName = "importCharterRequest")
        ImportCharterRequest importCharterRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * Экспорт статусов договоров управления, уставов, доп. соглашений
     * 
     * @param header0
     * @param header
     * @param exportStatusCAChRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportStatusCAChData")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", partName = "AckRequest")
    public AckRequest exportStatusCAChData(
        @WebParam(name = "exportStatusCAChRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/house-management/", partName = "exportStatusCAChRequest")
        ExportStatusCAChRequest exportStatusCAChRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_ИРАО_ДОМ_ЭКСП. Экспорт данных дома.
     * 
     * @param exportHouseRequest
     * @param header0
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportHouseData")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", partName = "AckRequest")
    public AckRequest exportHouseData(
        @WebParam(name = "exportHouseRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/house-management/", partName = "exportHouseRequest")
        ExportHouseRequest exportHouseRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_ИЛС_СЗЛС. передать данные лицевых счетов
     * 
     * @param header0
     * @param importAccountData
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importAccountData")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", partName = "AckResult")
    public AckRequest importAccountData(
        @WebParam(name = "importAccountRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/house-management/", partName = "importAccountData")
        ImportAccountRequest importAccountData,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_ИЛС_РЛС. получить перечень лицевых счетов
     * 
     * @param header0
     * @param header
     * @param exportAccountDataRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportAccountData")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", partName = "AckRequest")
    public AckRequest exportAccountData(
        @WebParam(name = "exportAccountRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/house-management/", partName = "exportAccountDataRequest")
        ExportAccountRequest exportAccountDataRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * Импорт ДОИ (Договор на пользование общим имуществом)
     * 
     * @param importPublicPropertyContractRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importPublicPropertyContract")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", partName = "AckResult")
    public AckRequest importPublicPropertyContract(
        @WebParam(name = "importPublicPropertyContractRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/house-management/", partName = "importPublicPropertyContractRequest")
        ImportPublicPropertyContractRequest importPublicPropertyContractRequest,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header)
        throws Fault
    ;

    /**
     * Экспорт списка ДОИ
     * 
     * @param header0
     * @param exportStatusPublicPropertyContractRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportStatusPublicPropertyContract")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", partName = "AckRequest")
    public AckRequest exportStatusPublicPropertyContract(
        @WebParam(name = "exportStatusPublicPropertyContractRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/house-management/", partName = "exportStatusPublicPropertyContractRequest")
        ExportStatusPublicPropertyContractRequest exportStatusPublicPropertyContractRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_ИО_И_1. Импорт новостей для информирования граждан
     * 
     * @param header0
     * @param importNotificationRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importNotificationData")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", partName = "AckResult")
    public AckRequest importNotificationData(
        @WebParam(name = "importNotificationRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/house-management/", partName = "importNotificationRequest")
        ImportNotificationRequest importNotificationRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * Импорт протокола ОСС
     * 
     * @param header0
     * @param importVotingProtocolRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importVotingProtocol")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", partName = "AckRequest")
    public AckRequest importVotingProtocol(
        @WebParam(name = "importVotingProtocolRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/house-management/", partName = "importVotingProtocolRequest")
        ImportVotingProtocolRequest importVotingProtocolRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * Экспорт протокола ОСС
     * 
     * @param header0
     * @param exportVotingProtocolRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportVotingProtocol")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", partName = "AckRequestr")
    public AckRequest exportVotingProtocol(
        @WebParam(name = "exportVotingProtocolRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/house-management/", partName = "exportVotingProtocolRequest")
        ExportVotingProtocolRequest exportVotingProtocolRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * Экспорт договоров управления, уставов, доп. соглашений
     * 
     * @param header0
     * @param header
     * @param tnsExportCAChDataRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportCAChData")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", partName = "tns:exportCAChDataResult")
    public AckRequest exportCAChData(
        @WebParam(name = "exportCAChRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/house-management/", partName = "tns:exportCAChDataRequest")
        ExportCAChRequest tnsExportCAChDataRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * Импорт данных дома для полномочия УО
     * 
     * @param header0
     * @param importHouseUODataRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importHouseUOData")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", partName = "AckRequest")
    public AckRequest importHouseUOData(
        @WebParam(name = "importHouseUORequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/house-management/", partName = "importHouseUODataRequest")
        ImportHouseUORequest importHouseUODataRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * Импорт данных дома для полномочия РСО
     * 
     * @param header0
     * @param header
     * @param importHouseRSODataRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importHouseRSOData")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", partName = "AckRequest")
    public AckRequest importHouseRSOData(
        @WebParam(name = "importHouseRSORequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/house-management/", partName = "importHouseRSODataRequest")
        ImportHouseRSORequest importHouseRSODataRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * Импорт данных дома для полномочия ОМС
     * 
     * @param header0
     * @param importHouseOMSDataRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importHouseOMSData")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", partName = "AckRequest")
    public AckRequest importHouseOMSData(
        @WebParam(name = "importHouseOMSRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/house-management/", partName = "importHouseOMSDataRequest")
        ImportHouseOMSRequest importHouseOMSDataRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

}
