
package ru.gosuslugi.dom.schema.integration._8_6_0_6.inspection_service_async;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import ru.gosuslugi.dom.schema.integration._8_6_0.AckRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0.GetStateRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0.RequestHeader;
import ru.gosuslugi.dom.schema.integration._8_6_0.ResultHeader;
import ru.gosuslugi.dom.schema.integration._8_6_0_6.inspection.ExportExaminationsRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0_6.inspection.ExportInspectionPlansRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0_6.inspection.GetStateResult;
import ru.gosuslugi.dom.schema.integration._8_6_0_6.inspection.ImportExaminationsRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0_6.inspection.ImportInspectionPlanRequest;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InspectionPortsTypeAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/inspection-service-async/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration._8_6_0.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration._8_6_0_6.inspection.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class
})
public interface InspectionPortsTypeAsync {


    /**
     * ВИ_ПИЖФ_ИПП. Импорт плана проверок.
     * 
     * @param header0
     * @param importInspectionPlanRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importInspectionPlan")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/", partName = "AckRequest")
    public AckRequest importInspectionPlan(
        @WebParam(name = "importInspectionPlanRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/inspection/", partName = "importInspectionPlanRequest")
        ImportInspectionPlanRequest importInspectionPlanRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_ПИЖФ_ЭПП. Экспорт плана проверок.
     * 
     * @param exportInspectionPlansRequest
     * @param header0
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportInspectionPlans")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/", partName = "AckRequest")
    public AckRequest exportInspectionPlans(
        @WebParam(name = "exportInspectionPlansRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/inspection/", partName = "exportInspectionPlansRequest")
        ExportInspectionPlansRequest exportInspectionPlansRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_ПИЖФ_ИП. Импорт проверок.
     * 
     * @param header0
     * @param importExaminationsRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importExaminations")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/", partName = "AckRequest")
    public AckRequest importExaminations(
        @WebParam(name = "importExaminationsRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/inspection/", partName = "importExaminationsRequest")
        ImportExaminationsRequest importExaminationsRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_ПИЖФ_ЭП. Экспорт проверок.
     * 
     * @param exportExaminationsRequest
     * @param header0
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportExaminations")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/", partName = "AckRequest")
    public AckRequest exportExaminations(
        @WebParam(name = "exportExaminationsRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/inspection/", partName = "exportExaminationsRequest")
        ExportExaminationsRequest exportExaminationsRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * 
     * @param getStateRequest
     * @param header0
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0_6.inspection.GetStateResult
     * @throws Fault
     */
    @WebMethod(action = "urn:getState")
    @WebResult(name = "getStateResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/inspection/", partName = "getStateResult")
    public GetStateResult getState(
        @WebParam(name = "getStateRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/", partName = "getStateRequest")
        GetStateRequest getStateRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

}
