
package ru.gosuslugi.dom.schema.integration._8_6_0_4.fas_service_async;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import ru.gosuslugi.dom.schema.integration._8_6_0.AckRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0.GetStateRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0.ISRequestHeader;
import ru.gosuslugi.dom.schema.integration._8_6_0.ResultHeader;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.fas.GetStateResult;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.fas.ImportRSORequest;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FASPortsTypeAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/fas-service-async/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration._8_6_0_4.fas.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration._8_6_0.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration._8_6_0_4.house_management.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration._8_6_0_4.services.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration._8_6_0_4.infrastructure.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration._8_6_0_4.inspection.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration._8_6_0_4.licenses.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration._8_6_0_4.organizations_registry.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration._8_6_0_4.organizations_registry_common.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration._8_6_0_4.device_metering.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration._8_6_0_4.disclosure.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration._8_6_0_4.nsi.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration._8_6_0_4.bills.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration._8_6_0_4.payment.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration._8_6_0_4.nsi_common.ObjectFactory.class
})
public interface FASPortsTypeAsync {


    /**
     * Статус операции
     * 
     * @param getStateRequest
     * @param header0
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0_4.fas.GetStateResult
     * @throws Fault
     */
    @WebMethod(action = "urn:getState")
    @WebResult(name = "getStateResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/fas/", partName = "getStateResult")
    public GetStateResult getState(
        @WebParam(name = "getStateRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", partName = "getStateRequest")
        GetStateRequest getStateRequest,
        @WebParam(name = "ISRequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, partName = "Header")
        ISRequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * Импорт сведений о лицах, осуществляющих поставки ресурсов.
     * 
     * @param header0
     * @param importRSORequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importRSO")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", partName = "AckRequest")
    public AckRequest importRSO(
        @WebParam(name = "importRSORequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/fas/", partName = "importRSORequest")
        ImportRSORequest importRSORequest,
        @WebParam(name = "ISRequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, partName = "Header")
        ISRequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

}
