
package ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import ru.gosuslugi.dom.schema.integration._8_7_0.RequestHeader;
import ru.gosuslugi.dom.schema.integration._8_7_0.ResultHeader;
import ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ExportAccountRequest;
import ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ExportAccountResult;
import ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ExportCAChRequest;
import ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ExportCAChResult;
import ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ExportHouseRequest;
import ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ExportHouseResult;
import ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ExportMeteringDeviceDataRequest;
import ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ExportMeteringDeviceDataResult;
import ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ExportStatusCAChRequest;
import ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ExportStatusCAChResult;
import ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ExportStatusPublicPropertyContractRequest;
import ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ExportStatusPublicPropertyContractResult;
import ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ExportSupplyResourceContractRequest;
import ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ExportSupplyResourceContractResult;
import ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ExportVotingProtocolRequest;
import ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ExportVotingProtocolResult;
import ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ImportAccountRequest;
import ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ImportCharterRequest;
import ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ImportContractRequest;
import ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ImportHouseOMSRequest;
import ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ImportHouseRSORequest;
import ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ImportHouseUORequest;
import ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ImportMeteringDeviceDataRequest;
import ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ImportNotificationRequest;
import ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ImportPublicPropertyContractRequest;
import ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ImportSupplyResourceContractRequest;
import ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ImportVotingProtocolRequest;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HouseManagementPortsType", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management-service/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration._8_7_0.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class
})
public interface HouseManagementPortsType {


    /**
     * Передать данные ПУ
     * 
     * @param header0
     * @param importMeteringDeviceDataRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importMeteringDeviceData")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "importMeteringDeviceDataResult")
    public ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ImportResult importMeteringDeviceData(
        @WebParam(name = "importMeteringDeviceDataRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "importMeteringDeviceDataRequest")
        ImportMeteringDeviceDataRequest importMeteringDeviceDataRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * Получить перечень ПУ
     * 
     * @param header0
     * @param header
     * @param exportMeteringDeviceDataRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ExportMeteringDeviceDataResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportMeteringDeviceData")
    @WebResult(name = "exportMeteringDeviceDataResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "exportMeteringDeviceDataResult")
    public ExportMeteringDeviceDataResult exportMeteringDeviceData(
        @WebParam(name = "exportMeteringDeviceDataRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "exportMeteringDeviceDataRequest")
        ExportMeteringDeviceDataRequest exportMeteringDeviceDataRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * Импорт договора управления 
     * 
     * @param header0
     * @param header
     * @param importContractRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importContractData")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "importResult")
    public ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ImportResult importContractData(
        @WebParam(name = "importContractRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "importContractRequest")
        ImportContractRequest importContractRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * Импорт устава 
     * 
     * @param importCharterRequest
     * @param header0
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importCharterData")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "ImportResult")
    public ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ImportResult importCharterData(
        @WebParam(name = "importCharterRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "importCharterRequest")
        ImportCharterRequest importCharterRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * Экспорт статусов договоров управления, уставов, доп. соглашений
     * 
     * @param header0
     * @param header
     * @param exportStatusCAChRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ExportStatusCAChResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportStatusCAChData")
    @WebResult(name = "exportStatusCAChResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "exportStatusCAChResult")
    public ExportStatusCAChResult exportStatusCAChData(
        @WebParam(name = "exportStatusCAChRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "exportStatusCAChRequest")
        ExportStatusCAChRequest exportStatusCAChRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_ИРАО_ДОМ_ЭКСП. Экспорт данных дома.
     * 
     * @param exportHouseDataRequest
     * @param header0
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ExportHouseResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportHouseData")
    @WebResult(name = "exportHouseResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "exportHouseDataResult")
    public ExportHouseResult exportHouseData(
        @WebParam(name = "exportHouseRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "exportHouseDataRequest")
        ExportHouseRequest exportHouseDataRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_ИЛС_СЗЛС. передать данные лицевых счетов
     * 
     * @param header0
     * @param importAccountDataRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importAccountData")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", partName = "importAccountDataResult")
    public ru.gosuslugi.dom.schema.integration._8_7_0.ImportResult importAccountData(
        @WebParam(name = "importAccountRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "importAccountDataRequest")
        ImportAccountRequest importAccountDataRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_ИЛС_РЛС. получить перечень лицевых счетов
     * 
     * @param header0
     * @param header
     * @param exportAccountDataRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ExportAccountResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportAccountData")
    @WebResult(name = "exportAccountResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "exportAccountDataResult")
    public ExportAccountResult exportAccountData(
        @WebParam(name = "exportAccountRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "exportAccountDataRequest")
        ExportAccountRequest exportAccountDataRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * Импорт ДОИ (Договор на пользование общим имуществом)
     * 
     * @param header0
     * @param importPublicPropertyContractRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importPublicPropertyContract")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", partName = "importPublicPropertyContractResult")
    public ru.gosuslugi.dom.schema.integration._8_7_0.ImportResult importPublicPropertyContract(
        @WebParam(name = "importPublicPropertyContractRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "importPublicPropertyContractRequest")
        ImportPublicPropertyContractRequest importPublicPropertyContractRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * Экспорт списка ДОИ
     * 
     * @param header0
     * @param exportStatusPublicPropertyContractRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ExportStatusPublicPropertyContractResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportStatusPublicPropertyContract")
    @WebResult(name = "exportStatusPublicPropertyContractResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "exportStatusPublicPropertyContractResult")
    public ExportStatusPublicPropertyContractResult exportStatusPublicPropertyContract(
        @WebParam(name = "exportStatusPublicPropertyContractRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "exportStatusPublicPropertyContractRequest")
        ExportStatusPublicPropertyContractRequest exportStatusPublicPropertyContractRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_ИО_И_1. Импорт новостей для информирования граждан
     * 
     * @param header0
     * @param importNotificationRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importNotificationData")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", partName = "importNotificationResult")
    public ru.gosuslugi.dom.schema.integration._8_7_0.ImportResult importNotificationData(
        @WebParam(name = "importNotificationRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "importNotificationRequest")
        ImportNotificationRequest importNotificationRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * Импорт протокола ОСС
     * 
     * @param header0
     * @param importVotingProtocolRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importVotingProtocol")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", partName = "importVotingProtocolResult")
    public ru.gosuslugi.dom.schema.integration._8_7_0.ImportResult importVotingProtocol(
        @WebParam(name = "importVotingProtocolRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "importVotingProtocolRequest")
        ImportVotingProtocolRequest importVotingProtocolRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * Экспорт протокола ОСС
     * 
     * @param header0
     * @param exportVotingProtocolRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ExportVotingProtocolResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportVotingProtocol")
    @WebResult(name = "exportVotingProtocolResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "exportVotingProtocolResult")
    public ExportVotingProtocolResult exportVotingProtocol(
        @WebParam(name = "exportVotingProtocolRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "exportVotingProtocolRequest")
        ExportVotingProtocolRequest exportVotingProtocolRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * Экспорт договоров управления, уставов, доп. соглашений
     * 
     * @param header0
     * @param header
     * @param exportCAChDataRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ExportCAChResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportCAChData")
    @WebResult(name = "exportCAChResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "exportCAChDataResult")
    public ExportCAChResult exportCAChData(
        @WebParam(name = "exportCAChRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "exportCAChDataRequest")
        ExportCAChRequest exportCAChDataRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * Импорт данных дома для полномочия УО
     * 
     * @param header0
     * @param importHouseUODataRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importHouseUOData")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "ImportResult")
    public ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ImportResult importHouseUOData(
        @WebParam(name = "importHouseUORequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "importHouseUODataRequest")
        ImportHouseUORequest importHouseUODataRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * Импорт данных дома для полномочия РСО
     * 
     * @param header0
     * @param header
     * @param importHouseRSODataRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importHouseRSOData")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "ImportResult")
    public ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ImportResult importHouseRSOData(
        @WebParam(name = "importHouseRSORequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "importHouseRSODataRequest")
        ImportHouseRSORequest importHouseRSODataRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * Импорт данных дома для полномочия ОМС
     * 
     * @param importHouseOMSDataRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importHouseOMSData")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "ImportResult")
    public ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ImportResult importHouseOMSData(
        @WebParam(name = "importHouseOMSRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "importHouseOMSDataRequest")
        ImportHouseOMSRequest importHouseOMSDataRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, mode = WebParam.Mode.INOUT, partName = "Header")
        Holder<RequestHeader> header)
        throws Fault
    ;

    /**
     * Импорт договора ресурсоснабжения с РСО
     * 
     * @param importSupplyResourceContractRequest
     * @param header0
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importSupplyResourceContractData")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", partName = "importSupplyResourceContractResult")
    public ru.gosuslugi.dom.schema.integration._8_7_0.ImportResult importSupplyResourceContractData(
        @WebParam(name = "importSupplyResourceContractRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "importSupplyResourceContractRequest")
        ImportSupplyResourceContractRequest importSupplyResourceContractRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * Экспорт договоров ресурсоснабжения
     * 
     * @param header0
     * @param exportSupplyResourceContractRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0_6.house_management.ExportSupplyResourceContractResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportSupplyResourceContractData")
    @WebResult(name = "exportSupplyResourceContractResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "exportSupplyResourceContractResult")
    public ExportSupplyResourceContractResult exportSupplyResourceContractData(
        @WebParam(name = "exportSupplyResourceContractRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/house-management/", partName = "exportSupplyResourceContractRequest")
        ExportSupplyResourceContractRequest exportSupplyResourceContractRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

}
