
package ru.gosuslugi.dom.schema.integration._8_7_0_6.nsi_service;

import ru.gosuslugi.dom.schema.integration._8_7_0.ImportResult;
import ru.gosuslugi.dom.schema.integration._8_7_0.RequestHeader;
import ru.gosuslugi.dom.schema.integration._8_7_0.ResultHeader;
import ru.gosuslugi.dom.schema.integration._8_7_0_6.nsi.*;

import javax.jws.*;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NsiPortsType", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/nsi-service/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@HandlerChain(file = "handler/ClientMessage_handler.xml")
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration._8_7_0.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration._8_7_0_6.nsi.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class
})
public interface NsiPortsType {


    /**
     * ВИ_НСИ_ИДС_1. Импортировать данные справочника 1 "Дополнительные услуги".
     * 
     * @param header0
     * @param header
     * @param importAdditionalServicesRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importAdditionalServices")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", partName = "importAdditionalServicesResult")
    public ImportResult importAdditionalServices(
        @WebParam(name = "importAdditionalServicesRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/nsi/", partName = "importAdditionalServicesRequest")
        ImportAdditionalServicesRequest importAdditionalServicesRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_НСИ_ИДС_51. Импортировать данные справочника 51 "Коммунальные услуги".
     * 
     * @param header0
     * @param importMunicipalServicesRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importMunicipalServices")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", partName = "importMunicipalServicesResult")
    public ImportResult importMunicipalServices(
        @WebParam(name = "importMunicipalServicesRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/nsi/", partName = "importMunicipalServicesRequest")
        ImportMunicipalServicesRequest importMunicipalServicesRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_НСИ_ИДС_59. Импортировать данные справочника 59 "Работы и услуги организации".
     * 
     * @param header0
     * @param importOrganizationWorksRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importOrganizationWorks")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", partName = "importOrganizationWorksResult")
    public ImportResult importOrganizationWorks(
        @WebParam(name = "importOrganizationWorksRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/nsi/", partName = "importOrganizationWorksRequest")
        ImportOrganizationWorksRequest importOrganizationWorksRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * Экспортировать данные справочников поставщика информации  (1,51,59)
     * 
     * @param header0
     * @param exportDataProviderNsiItemRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0_6.nsi.ExportNsiItemResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportDataProviderNsiItem")
    @WebResult(name = "exportNsiItemResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/nsi/", partName = "exportDataProviderNsiItemResult")
    public ExportNsiItemResult exportDataProviderNsiItem(
        @WebParam(name = "exportDataProviderNsiItemRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/nsi/", partName = "exportDataProviderNsiItemRequest")
        ExportDataProviderNsiItemRequest exportDataProviderNsiItemRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

}
