
package ru.gosuslugi.dom.schema.integration._8_5_0_2.disclosure_service_async;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DisclosureServiceAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.2/disclosure-service-async/", wsdlLocation = "https://54.76.42.99:60045/ext-bus-information-disclosure-service/services/DisclosureAsync?wsdl")
public class DisclosureServiceAsync
    extends Service
{

    private final static URL DISCLOSURESERVICEASYNC_WSDL_LOCATION;
    private final static WebServiceException DISCLOSURESERVICEASYNC_EXCEPTION;
    private final static QName DISCLOSURESERVICEASYNC_QNAME = new QName("http://dom.gosuslugi.ru/schema/integration/8.5.0.2/disclosure-service-async/", "DisclosureServiceAsync");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://54.76.42.99:60045/ext-bus-information-disclosure-service/services/DisclosureAsync?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DISCLOSURESERVICEASYNC_WSDL_LOCATION = url;
        DISCLOSURESERVICEASYNC_EXCEPTION = e;
    }

    public DisclosureServiceAsync() {
        super(__getWsdlLocation(), DISCLOSURESERVICEASYNC_QNAME);
    }

    public DisclosureServiceAsync(WebServiceFeature... features) {
        super(__getWsdlLocation(), DISCLOSURESERVICEASYNC_QNAME, features);
    }

    public DisclosureServiceAsync(URL wsdlLocation) {
        super(wsdlLocation, DISCLOSURESERVICEASYNC_QNAME);
    }

    public DisclosureServiceAsync(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DISCLOSURESERVICEASYNC_QNAME, features);
    }

    public DisclosureServiceAsync(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DisclosureServiceAsync(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DisclosurePortsTypeAsync
     */
    @WebEndpoint(name = "DisclosurePortAsync")
    public DisclosurePortsTypeAsync getDisclosurePortAsync() {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/8.5.0.2/disclosure-service-async/", "DisclosurePortAsync"), DisclosurePortsTypeAsync.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DisclosurePortsTypeAsync
     */
    @WebEndpoint(name = "DisclosurePortAsync")
    public DisclosurePortsTypeAsync getDisclosurePortAsync(WebServiceFeature... features) {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/8.5.0.2/disclosure-service-async/", "DisclosurePortAsync"), DisclosurePortsTypeAsync.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DISCLOSURESERVICEASYNC_EXCEPTION!= null) {
            throw DISCLOSURESERVICEASYNC_EXCEPTION;
        }
        return DISCLOSURESERVICEASYNC_WSDL_LOCATION;
    }

}
