
package ru.gosuslugi.dom.schema.integration.services.organizations_registry_common_service;

import ru.gosuslugi.dom.schema.integration.base.HeaderType;
import ru.gosuslugi.dom.schema.integration.base.ResultHeader;
import ru.gosuslugi.dom.schema.integration.services.organizations_registry_common.ExportDataProviderRequest;
import ru.gosuslugi.dom.schema.integration.services.organizations_registry_common.ExportDataProviderResult;
import ru.gosuslugi.dom.schema.integration.services.organizations_registry_common.ExportOrgRegistryRequest;
import ru.gosuslugi.dom.schema.integration.services.organizations_registry_common.ExportOrgRegistryResult;

import javax.jws.*;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RegOrgPortsType", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.7/organizations-registry-common-service/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@HandlerChain(file = "handler/ClientMessage_handler.xml")
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration.services.organizations_registry_common.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.base.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class
})
public interface RegOrgPortsType {


    /**
     * экспорт сведений об организациях
     * 
     * @param exportOrgRegistryRequest
     * @param header0
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.services.organizations_registry_common.ExportOrgRegistryResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportOrgRegistry")
    @WebResult(name = "exportOrgRegistryResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.7/organizations-registry-common/", partName = "exportOrgRegistryResult")
    public ExportOrgRegistryResult exportOrgRegistry(
        @WebParam(name = "exportOrgRegistryRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.7/organizations-registry-common/", partName = "exportOrgRegistryRequest")
        ExportOrgRegistryRequest exportOrgRegistryRequest,
        @WebParam(name = "ISRequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.7/", header = true, partName = "Header")
        HeaderType header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.7/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * экспорт сведений о поставщиках данных
     * 
     * @param exportDataProviderRequest
     * @param header0
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.services.organizations_registry_common.ExportDataProviderResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportDataProvider")
    @WebResult(name = "exportDataProviderResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.7/organizations-registry-common/", partName = "exportDataProviderResult")
    public ExportDataProviderResult exportDataProvider(
        @WebParam(name = "exportDataProviderRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.7/organizations-registry-common/", partName = "exportDataProviderRequest")
        ExportDataProviderRequest exportDataProviderRequest,
        @WebParam(name = "ISRequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.7/", header = true, partName = "Header")
        HeaderType header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.7/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

}
