
package ru.gosuslugi.dom.schema.integration._8_6_0_4.licenses_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import ru.gosuslugi.dom.schema.integration._8_6_0.RequestHeader;
import ru.gosuslugi.dom.schema.integration._8_6_0.ResultHeader;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.licenses.ExportDisqualifiedPersonRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.licenses.ExportDisqualifiedPersonResult;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.licenses.ExportLicenseRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0_4.licenses.ExportLicenseResult;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LicensePortsTypes", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/licenses-service/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration._8_6_0_4.licenses.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration._8_6_0.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class
})
public interface LicensePortsTypes {


    /**
     * 
     * @param exporttLicenseRequestType
     * @param header0
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0_4.licenses.ExportLicenseResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportLicense")
    @WebResult(name = "exportLicenseResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/licenses/", partName = "exportLicenseResult")
    public ExportLicenseResult exportLicense(
        @WebParam(name = "exportLicenseRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/licenses/", partName = "exporttLicenseRequestType")
        ExportLicenseRequest exporttLicenseRequestType,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * 
     * @param header0
     * @param exportDisqualifiedPersonRequestType
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0_4.licenses.ExportDisqualifiedPersonResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportDisqualifiedPerson")
    @WebResult(name = "exportDisqualifiedPersonResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/licenses/", partName = "exportDisqualifiedPersonResultType")
    public ExportDisqualifiedPersonResult exportDisqualifiedPerson(
        @WebParam(name = "exportDisqualifiedPersonRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/licenses/", partName = "exportDisqualifiedPersonRequestType")
        ExportDisqualifiedPersonRequest exportDisqualifiedPersonRequestType,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

}
