
package ru.gosuslugi.dom.schema.integration._8_7_0_6.organizations_registry_common_service_async;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RegOrgServiceAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.6/organizations-registry-common-service-async/", wsdlLocation = "https://54.76.42.99:60045/ext-bus-org-registry-common-service/services/OrgRegistryCommonAsync")
@HandlerChain(file = "handler/ClientMessage_handler.xml")
public class RegOrgServiceAsync
    extends Service
{

    private final static URL REGORGSERVICEASYNC_WSDL_LOCATION;
    private final static WebServiceException REGORGSERVICEASYNC_EXCEPTION;
    private final static QName REGORGSERVICEASYNC_QNAME = new QName("http://dom.gosuslugi.ru/schema/integration/8.7.0.6/organizations-registry-common-service-async/", "RegOrgServiceAsync");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://54.76.42.99:60045/ext-bus-org-registry-common-service/services/OrgRegistryCommonAsync");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REGORGSERVICEASYNC_WSDL_LOCATION = url;
        REGORGSERVICEASYNC_EXCEPTION = e;
    }

    public RegOrgServiceAsync() {
        super(__getWsdlLocation(), REGORGSERVICEASYNC_QNAME);
    }

    public RegOrgServiceAsync(WebServiceFeature... features) {
        super(__getWsdlLocation(), REGORGSERVICEASYNC_QNAME, features);
    }

    public RegOrgServiceAsync(URL wsdlLocation) {
        super(wsdlLocation, REGORGSERVICEASYNC_QNAME);
    }

    public RegOrgServiceAsync(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REGORGSERVICEASYNC_QNAME, features);
    }

    public RegOrgServiceAsync(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegOrgServiceAsync(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RegOrgPortsTypeAsync
     */
    @WebEndpoint(name = "RegOrgAsyncPort")
    public RegOrgPortsTypeAsync getRegOrgAsyncPort() {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/8.7.0.6/organizations-registry-common-service-async/", "RegOrgAsyncPort"), RegOrgPortsTypeAsync.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegOrgPortsTypeAsync
     */
    @WebEndpoint(name = "RegOrgAsyncPort")
    public RegOrgPortsTypeAsync getRegOrgAsyncPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/8.7.0.6/organizations-registry-common-service-async/", "RegOrgAsyncPort"), RegOrgPortsTypeAsync.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REGORGSERVICEASYNC_EXCEPTION!= null) {
            throw REGORGSERVICEASYNC_EXCEPTION;
        }
        return REGORGSERVICEASYNC_WSDL_LOCATION;
    }

}
