
package ru.gosuslugi.dom.schema.integration._8_7_0_4.nsi_service_async;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import ru.gosuslugi.dom.schema.integration._8_7_0.AckRequest;
import ru.gosuslugi.dom.schema.integration._8_7_0.GetStateRequest;
import ru.gosuslugi.dom.schema.integration._8_7_0.RequestHeader;
import ru.gosuslugi.dom.schema.integration._8_7_0.ResultHeader;
import ru.gosuslugi.dom.schema.integration._8_7_0_4.nsi.ExportDataProviderNsiItemRequest;
import ru.gosuslugi.dom.schema.integration._8_7_0_4.nsi.GetStateResult;
import ru.gosuslugi.dom.schema.integration._8_7_0_4.nsi.ImportAdditionalServicesRequest;
import ru.gosuslugi.dom.schema.integration._8_7_0_4.nsi.ImportMunicipalServicesRequest;
import ru.gosuslugi.dom.schema.integration._8_7_0_4.nsi.ImportOrganizationWorksRequest;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NsiPortsTypeAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/nsi-service-async/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration._8_7_0.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration._8_7_0_4.nsi.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class
})
public interface NsiPortsTypeAsync {


    /**
     * ВИ_НСИ_ИДС_1. Импортировать данные справочника 1 "Дополнительные услуги".
     * 
     * @param header0
     * @param header
     * @param importAdditionalServicesRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importAdditionalServices")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/", partName = "importAdditionalServicesResult")
    public AckRequest importAdditionalServices(
        @WebParam(name = "importAdditionalServicesRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/nsi/", partName = "importAdditionalServicesRequest")
        ImportAdditionalServicesRequest importAdditionalServicesRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_НСИ_ИДС_51. Импортировать данные справочника 51 "Коммунальные услуги".
     * 
     * @param header0
     * @param importMunicipalServicesRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importMunicipalServices")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/", partName = "importMunicipalServicesResult")
    public AckRequest importMunicipalServices(
        @WebParam(name = "importMunicipalServicesRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/nsi/", partName = "importMunicipalServicesRequest")
        ImportMunicipalServicesRequest importMunicipalServicesRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_НСИ_ИДС_59. Импортировать данные справочника 59 "Работы и услуги организации".
     * 
     * @param header0
     * @param importOrganizationWorksRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importOrganizationWorks")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/", partName = "importOrganizationWorksResult")
    public AckRequest importOrganizationWorks(
        @WebParam(name = "importOrganizationWorksRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/nsi/", partName = "importOrganizationWorksRequest")
        ImportOrganizationWorksRequest importOrganizationWorksRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * 
     * @param getStateRequest
     * @param header0
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0_4.nsi.GetStateResult
     * @throws Fault
     */
    @WebMethod(action = "urn:getState")
    @WebResult(name = "getStateResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/nsi/", partName = "getStateResult")
    public GetStateResult getState(
        @WebParam(name = "getStateRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/", partName = "getStateRequest")
        GetStateRequest getStateRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * Экспортировать данные справочников поставщика информации  (1,51,59)
     * 
     * @param header0
     * @param exportDataProviderNsiItemRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportDataProviderNsiItem")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/", partName = "AckRequest")
    public AckRequest exportDataProviderNsiItem(
        @WebParam(name = "exportDataProviderNsiItemRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/nsi/", partName = "exportDataProviderNsiItemRequest")
        ExportDataProviderNsiItemRequest exportDataProviderNsiItemRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

}
