
package ru.gosuslugi.dom.schema.integration.services.inspection_service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Сервис работы с планами проверок и проверками
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InspectionService", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.7/inspection-service/", wsdlLocation = "https://54.76.42.99:60045/ext-bus-inspection-service/services/Inspection")
public class InspectionService
    extends Service
{

    private final static URL INSPECTIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException INSPECTIONSERVICE_EXCEPTION;
    private final static QName INSPECTIONSERVICE_QNAME = new QName("http://dom.gosuslugi.ru/schema/integration/8.7.0.7/inspection-service/", "InspectionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://54.76.42.99:60045/ext-bus-inspection-service/services/Inspection");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INSPECTIONSERVICE_WSDL_LOCATION = url;
        INSPECTIONSERVICE_EXCEPTION = e;
    }

    public InspectionService() {
        super(__getWsdlLocation(), INSPECTIONSERVICE_QNAME);
    }

    public InspectionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INSPECTIONSERVICE_QNAME, features);
    }

    public InspectionService(URL wsdlLocation) {
        super(wsdlLocation, INSPECTIONSERVICE_QNAME);
    }

    public InspectionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INSPECTIONSERVICE_QNAME, features);
    }

    public InspectionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InspectionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InspectionPortsType
     */
    @WebEndpoint(name = "InspectionPort")
    public InspectionPortsType getInspectionPort() {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/8.7.0.7/inspection-service/", "InspectionPort"), InspectionPortsType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InspectionPortsType
     */
    @WebEndpoint(name = "InspectionPort")
    public InspectionPortsType getInspectionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/8.7.0.7/inspection-service/", "InspectionPort"), InspectionPortsType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INSPECTIONSERVICE_EXCEPTION!= null) {
            throw INSPECTIONSERVICE_EXCEPTION;
        }
        return INSPECTIONSERVICE_WSDL_LOCATION;
    }

}
