
package ru.gosuslugi.dom.schema.integration.services.inspection_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import ru.gosuslugi.dom.schema.integration.base.ImportResult;
import ru.gosuslugi.dom.schema.integration.base.RequestHeader;
import ru.gosuslugi.dom.schema.integration.base.ResultHeader;
import ru.gosuslugi.dom.schema.integration.services.inspection.ExportExaminationsRequest;
import ru.gosuslugi.dom.schema.integration.services.inspection.ExportExaminationsResult;
import ru.gosuslugi.dom.schema.integration.services.inspection.ExportInspectionPlansRequest;
import ru.gosuslugi.dom.schema.integration.services.inspection.ExportInspectionPlansResult;
import ru.gosuslugi.dom.schema.integration.services.inspection.ImportExaminationsRequest;
import ru.gosuslugi.dom.schema.integration.services.inspection.ImportInspectionPlanRequest;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InspectionPortsType", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.7/inspection-service/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration.base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.services.inspection.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class
})
public interface InspectionPortsType {


    /**
     * ВИ_ПИЖФ_ИПП. Импорт плана проверок.
     * 
     * @param header0
     * @param importInspectionPlanRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importInspectionPlan")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.7/", partName = "importInspectionPlanResult")
    public ImportResult importInspectionPlan(
        @WebParam(name = "importInspectionPlanRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.7/inspection/", partName = "importInspectionPlanRequest")
        ImportInspectionPlanRequest importInspectionPlanRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.7/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.7/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_ПИЖФ_ЭПП. Экспорт плана проверок.
     * 
     * @param exportInspectionPlansRequest
     * @param header0
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.services.inspection.ExportInspectionPlansResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportInspectionPlans")
    @WebResult(name = "exportInspectionPlansResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.7/inspection/", partName = "exportInspectionPlansResult")
    public ExportInspectionPlansResult exportInspectionPlans(
        @WebParam(name = "exportInspectionPlansRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.7/inspection/", partName = "exportInspectionPlansRequest")
        ExportInspectionPlansRequest exportInspectionPlansRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.7/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.7/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_ПИЖФ_ИП. Импорт проверок.
     * 
     * @param header0
     * @param importExaminationsRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importExaminations")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.7/", partName = "importExaminationsResult")
    public ImportResult importExaminations(
        @WebParam(name = "importExaminationsRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.7/inspection/", partName = "importExaminationsRequest")
        ImportExaminationsRequest importExaminationsRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.7/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.7/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_ПИЖФ_ЭП. Экспорт проверок.
     * 
     * @param exportExaminationsRequest
     * @param header0
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.services.inspection.ExportExaminationsResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportExaminations")
    @WebResult(name = "exportExaminationsResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.7/inspection/", partName = "exportExaminationsResult")
    public ExportExaminationsResult exportExaminations(
        @WebParam(name = "exportExaminationsRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.7/inspection/", partName = "exportExaminationsRequest")
        ExportExaminationsRequest exportExaminationsRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.7/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.7/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

}
