
package ru.gosuslugi.dom.schema.integration._8_5_0_4.nsi_service;

import javax.jws.*;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import ru.gosuslugi.dom.schema.integration._8_5_0.ImportResult;
import ru.gosuslugi.dom.schema.integration._8_5_0.RequestHeader;
import ru.gosuslugi.dom.schema.integration._8_5_0_4.nsi.ExportNsiItemRequest;
import ru.gosuslugi.dom.schema.integration._8_5_0_4.nsi.ExportNsiItemResult;
import ru.gosuslugi.dom.schema.integration._8_5_0_4.nsi.ExportNsiListRequest;
import ru.gosuslugi.dom.schema.integration._8_5_0_4.nsi.ExportNsiListResult;
import ru.gosuslugi.dom.schema.integration._8_5_0_4.nsi.ImportAdditionalServicesRequest;
import ru.gosuslugi.dom.schema.integration._8_5_0_4.nsi.ImportMunicipalServicesRequest;
import ru.gosuslugi.dom.schema.integration._8_5_0_4.nsi.ImportOrganizationWorksRequest;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NsiPortsType", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/nsi-service/")
@HandlerChain(file = "handler/ClientMessage_handler.xml")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration._8_5_0.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration._8_5_0_4.nsi.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class
})
public interface NsiPortsType {


    /**
     * ВИ_НСИ_ППС. Получить перечень справочников с указанием даты последнего изменения каждого из них.
     * 
     * @param exportNsiListRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_5_0_4.nsi.ExportNsiListResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportNsiList")
    @WebResult(name = "exportNsiListResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/nsi/", partName = "exportNsiListResult")
    public ExportNsiListResult exportNsiList(
        @WebParam(name = "exportNsiListRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/nsi/", partName = "exportNsiListRequest")
        ExportNsiListRequest exportNsiListRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", header = true, mode = WebParam.Mode.INOUT, partName = "Header")
        Holder<RequestHeader> header)
        throws Fault
    ;

    /**
     * ВИ_НСИ_ПДС. Получить данные справочника.
     * 
     * @param exportNsiItemRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_5_0_4.nsi.ExportNsiItemResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportNsiItem")
    @WebResult(name = "exportNsiItemResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/nsi/", partName = "exportNsiItemResult")
    public ExportNsiItemResult exportNsiItem(
        @WebParam(name = "exportNsiItemRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/nsi/", partName = "exportNsiItemRequest")
        ExportNsiItemRequest exportNsiItemRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", header = true, mode = WebParam.Mode.INOUT, partName = "Header")
        Holder<RequestHeader> header)
        throws Fault
    ;

    /**
     * ВИ_НСИ_ИДС_1. Импортировать данные справочника 1 "Дополнительные услуги".
     * 
     * @param header
     * @param importAdditionalServicesRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_5_0.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importAdditionalServices")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", partName = "importAdditionalServicesResult")
    public ImportResult importAdditionalServices(
        @WebParam(name = "importAdditionalServicesRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/nsi/", partName = "importAdditionalServicesRequest")
        ImportAdditionalServicesRequest importAdditionalServicesRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", header = true, mode = WebParam.Mode.INOUT, partName = "Header")
        Holder<RequestHeader> header)
        throws Fault
    ;

    /**
     * ВИ_НСИ_ИДС_51. Импортировать данные справочника 51 "Коммунальные услуги".
     * 
     * @param importMunicipalServicesRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_5_0.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importMunicipalServices")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", partName = "importMunicipalServicesResult")
    public ImportResult importMunicipalServices(
        @WebParam(name = "importMunicipalServicesRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/nsi/", partName = "importMunicipalServicesRequest")
        ImportMunicipalServicesRequest importMunicipalServicesRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", header = true, mode = WebParam.Mode.INOUT, partName = "Header")
        Holder<RequestHeader> header)
        throws Fault
    ;

    /**
     * ВИ_НСИ_ИДС_59. Импортировать данные справочника 59 "Работы и услуги организации".
     * 
     * @param importOrganizationWorksRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_5_0.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importOrganizationWorks")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", partName = "importOrganizationWorksResult")
    public ImportResult importOrganizationWorks(
        @WebParam(name = "importOrganizationWorksRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/nsi/", partName = "importOrganizationWorksRequest")
        ImportOrganizationWorksRequest importOrganizationWorksRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.5.0.4/", header = true, mode = WebParam.Mode.INOUT, partName = "Header")
        Holder<RequestHeader> header)
        throws Fault
    ;

}
