
package ru.gosuslugi.dom.schema.integration._8_7_0_4.device_metering_service_async;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import ru.gosuslugi.dom.schema.integration._8_7_0.AckRequest;
import ru.gosuslugi.dom.schema.integration._8_7_0.GetStateRequest;
import ru.gosuslugi.dom.schema.integration._8_7_0.RequestHeader;
import ru.gosuslugi.dom.schema.integration._8_7_0.ResultHeader;
import ru.gosuslugi.dom.schema.integration._8_7_0_4.device_metering.ExportMeteringDeviceHistoryRequest;
import ru.gosuslugi.dom.schema.integration._8_7_0_4.device_metering.GetStateResult;
import ru.gosuslugi.dom.schema.integration._8_7_0_4.device_metering.ImportMeteringDeviceValuesRequest;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DeviceMeteringPortTypesAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/device-metering-service-async/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration._8_7_0_4.device_metering.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration._8_7_0.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class
})
public interface DeviceMeteringPortTypesAsync {


    /**
     * Передать показания ПУ
     * 
     * @param importMeteringDeviceValuesRequest
     * @param header0
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importMeteringDeviceValues")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/", partName = "AckRequest")
    public AckRequest importMeteringDeviceValues(
        @WebParam(name = "importMeteringDeviceValuesRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/device-metering/", partName = "importMeteringDeviceValuesRequest")
        ImportMeteringDeviceValuesRequest importMeteringDeviceValuesRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * Получить историю показаний ПУ
     * 
     * @param header0
     * @param header
     * @param exportMeteringDeviceHistoryRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportMeteringDeviceHistory")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/", partName = "AckRequest")
    public AckRequest exportMeteringDeviceHistory(
        @WebParam(name = "exportMeteringDeviceHistoryRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/device-metering/", partName = "exportMeteringDeviceHistoryRequest")
        ExportMeteringDeviceHistoryRequest exportMeteringDeviceHistoryRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * 
     * @param getStateRequest
     * @param header0
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_7_0_4.device_metering.GetStateResult
     * @throws Fault
     */
    @WebMethod(action = "urn:getState")
    @WebResult(name = "getStateResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/device-metering/", partName = "getStateResult")
    public GetStateResult getState(
        @WebParam(name = "getStateRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/", partName = "getStateRequest")
        GetStateRequest getStateRequest,
        @WebParam(name = "RequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/", header = true, partName = "Header")
        RequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.7.0.4/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

}
