
package ru.gosuslugi.dom.schema.integration._8_6_0_6.nsi_common_service_async;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import ru.gosuslugi.dom.schema.integration._8_6_0.AckRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0.GetStateRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0.ISRequestHeader;
import ru.gosuslugi.dom.schema.integration._8_6_0.ResultHeader;
import ru.gosuslugi.dom.schema.integration._8_6_0_6.nsi_common.ExportNsiItemRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0_6.nsi_common.ExportNsiListRequest;
import ru.gosuslugi.dom.schema.integration._8_6_0_6.nsi_common.GetStateResult;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NsiPortsTypeAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/nsi-common-service-async/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration._8_6_0.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration._8_6_0_6.nsi_common.ObjectFactory.class
})
public interface NsiPortsTypeAsync {


    /**
     * ВИ_НСИ_ППС. Получить перечень справочников с указанием даты последнего изменения каждого из них.
     * 
     * @param exportNsiListRequest
     * @param header0
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportNsiList")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/", partName = "AckRequest")
    public AckRequest exportNsiList(
        @WebParam(name = "exportNsiListRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/nsi-common/", partName = "exportNsiListRequest")
        ExportNsiListRequest exportNsiListRequest,
        @WebParam(name = "ISRequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/", header = true, partName = "Header")
        ISRequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * ВИ_НСИ_ПДС. Получить данные справочника.
     * 
     * @param header0
     * @param exportNsiItemRequest
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportNsiItem")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/", partName = "AckRequest")
    public AckRequest exportNsiItem(
        @WebParam(name = "exportNsiItemRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/nsi-common/", partName = "exportNsiItemRequest")
        ExportNsiItemRequest exportNsiItemRequest,
        @WebParam(name = "ISRequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/", header = true, partName = "Header")
        ISRequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

    /**
     * 
     * @param getStateRequest
     * @param header0
     * @param header
     * @return
     *     returns ru.gosuslugi.dom.schema.integration._8_6_0_6.nsi_common.GetStateResult
     * @throws Fault
     */
    @WebMethod(action = "urn:getState")
    @WebResult(name = "getStateResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/nsi-common/", partName = "getStateResult")
    public GetStateResult getState(
        @WebParam(name = "getStateRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/", partName = "getStateRequest")
        GetStateRequest getStateRequest,
        @WebParam(name = "ISRequestHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/", header = true, partName = "Header")
        ISRequestHeader header,
        @WebParam(name = "ResultHeader", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/8.6.0.6/", header = true, mode = WebParam.Mode.OUT, partName = "Header")
        Holder<ResultHeader> header0)
        throws Fault
    ;

}
